"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Appheader from "@/components/app.header";
import AppFooter from "@/components/AppFooter";
import Container from "react-bootstrap/Container";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Appheader />

        <Container>{children}</Container>
        <AppFooter />
      </body>
    </html>
  );
}
